b_04_textbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('testapp/', include('testapp.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

testapp/urls.py
from django.urls import path, reverse

from . import views

app_name = 'testapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post', views.PostCreate.as_view(), name='post'),
    path('createPost', views.createPost, name='createPost'),
    path('createPost/<dept>/<id>', views.createPostFromClass, name='createPostFromClass'),
    path('course', views.course, name='course'),
    path('classsubject', views.ClassSubjectCreate.as_view(success_url = '/testapp/course'), name='classsubject'),
    path('<int:fav_id>/favorite_post', views.favorite_post, name='favorite_post'),
    path('<int:fav_id>/favorite_post_from_search', views.favorite_post_from_search, name='favorite_post_from_search'),
    path('<int:fav_id>/remove_favorite', views.remove_favorite, name='remove_favorite'),
    path('<int:fav_id>/remove_favorite_from_fav', views.remove_favorite_from_fav, name='remove_favorite_from_fav'),
    path('<int:fav_id>/remove_favorite_from_search',views.remove_favorite_from_search, name = 'remove_favorite_from_search'),
    path('favorites', views.FavoritesView.as_view(), name='favorites'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('profile/<pk>/edit', views.UpdateProfileView.as_view(), name='update_profile_view'),
    path('profile/<pk>/update', views.updateProfile, name='update_profile'),
    path('profile/<pk>/add_friend', views.addFriend, name='add_friend'),
    path('profile/<pk>/alt', views.addNewFriend.as_view(), name='add_new_friend'),
    path('threads', views.ThreadList.as_view(), name='threads'),
    path('threads/create', views.ThreadCreate.as_view(), name='thread_creation'),
    path('threads/createThread', views.createThread, name='create_thread'),
    path('threads/<pk>', views.ThreadView.as_view(), name='thread_view'),
    path('threads/<pk>/createMessage', views.createMessage, name='create_message'),
    path('post_search', views.searchView.as_view(), name='search'),
]

testapp/models.py
import datetime
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


#https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
#Link to profile page model and view tutorial
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default = "John Wick")
    years = (
        ('First', '1st'),
        ('Second', '2nd'),
        ('Third', '3rd'),
        ('Fourth', '4th'),
        ('Other', 'Other'),
    )
    year = models.CharField(max_length=6,choices = years, default = 'First')
    major = models.CharField(max_length=100, default = 'CS')
    friends = models.ManyToManyField(User, related_name = 'friends', blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
   if created:
      Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
   instance.profile.save()

class Post(models.Model):
    post_title = models.CharField(max_length=200)
    post_text = models.TextField()
    pub_date =  models.DateTimeField('date published', auto_now_add=True)
    book_ISBN = models.CharField(max_length=13, default = '')
    # sell_status = models.BooleanField(default=False)
    # deptList = (
    #     ('BME', 'Biomedical Engineering'),
    #     ('CHE', 'Chemical Engineering'),
    #     ('CS', 'Computer Science'),
    #     ('ECE', 'Electrical and Computer Engineering'),
    #     ('STS', 'Engineering and Society'),
    #     ('MSE', 'Material Sciences Engineering'),
    #     ('MAE', 'Mechanical and Aerospace Engineering'),
    #     ('SYS', 'Systems Engineering'),
    #     ('CE', 'Civil Engineering'),
    #     ('APMA', 'Applied Mathematics'),
    # )
    # associated_dept = models.CharField(max_length = 4, choices = deptList, default='CS')
    associated_dept = models.CharField(max_length=50)
    course_id = models.CharField(max_length = 4, default='')
    favorite = models.ManyToManyField(User, related_name = 'favorite_post', blank=True)
    post_creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.post_title

    def was_published_recently(self):
        now = datetime.timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class ClassSubject(models.Model):
    class_subject = models.CharField(max_length = 50)
    def __str__(self):
        return self.class_subject

#https://legionscript.medium.com/building-a-social-media-app-with-django-and-python-part-14-direct-messages-pt-1-1a6b8bd9fc40
#General guidance on messaging models and constructing messaging urls
class Thread(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    subject_text = models.CharField(max_length=500, default="No subject")
    was_read = models.BooleanField(default=False)

class Message(models.Model):
    thread = models.ForeignKey('Thread', on_delete=models.CASCADE, related_name='+')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    message_text = models.CharField(max_length=1500)
    sent_date = models.DateTimeField('date sent', auto_now_add=True)
    was_read = models.BooleanField(default=False)

# class FavoritePost(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="favoritepost", null=True)
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     favorite = models.BooleanField

testapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User
import requests
from .models import ClassSubject, Post, Profile, Thread, Message
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
import re
#note

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'testapp/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.all()

class PostCreate(LoginRequiredMixin, generic.TemplateView):
    model = Post
    template_name = 'testapp/post_form.html'

def createPost(request):
    try:
        if request.POST['post_title']=="" or request.POST['post_text']=="" or request.POST['associated_dept']=="" or request.POST['course_id']=="":
            return render(request,'testapp/post_form.html', {
            'error_message': "You didn't fill in an input.",
            })
        else:
            Post.objects.create(post_title=request.POST['post_title'],
                                post_text=request.POST['post_text'],
                                book_ISBN=request.POST['book_ISBN'],
                                associated_dept=request.POST['associated_dept'],
                                course_id=request.POST['course_id'],
                                post_creator=request.user)
    except(KeyError, ):
        return render(request,'testapp/post_form.html', {
            'error_message': "You didn't fill in an input.",
        })
    else:
        return HttpResponseRedirect(reverse('testapp:index'))

def createPostFromClass(request, dept, id):
    context = {
        'associated_dept': dept,
        'course_id' : id
    }
    return render(request, 'testapp/post_form.html', context)

class ClassSubjectCreate(LoginRequiredMixin, CreateView):
    model = ClassSubject
    # success_url = 'course'
    fields = ['class_subject']

    # def get_context_data(self, **kwargs):
    #     content = super().get_context_data(**kwargs)
    #     response = requests.get('https://luthers-list.herokuapp.com/api/deptlist?format=json')
    #     classdata = response.json()
    #     # for item in classdata:
    #     #     print(list(item.values()))
    #     #print(classdata)
    #     #print({'subject':classdata})
    #     return ({'subject':classdata})

    def form_valid(self, form):
        response = super().form_valid(form)
        self.request.session['class_subject'] = self.request.POST['class_subject']
        return response

    # def listCreate(request):
    #     subject = request.session.get('class_subject')
    #     response = requests.get('http://luthers-list.herokuapp.com/api/deptlist?format=json')
    #     classdata = response.json()
    #     print(classdata)
    #     return render(request, 'testapp/classsubject.html', {'subject':classdata[0]['subject']})

def course(request):
    # Find a way to take this as input
    # code = request.POST.get('class_subject', '')
    # try:
    #     coursedata = ClassSubject.objects.get(class_subject = code)
    #     subject = coursedata.class_subject
    # except ClassSubject.DoesNotExist:
    #     subject = "CS"
    subject = request.session.get('class_subject')
    response = requests.get('https://luthers-list.herokuapp.com/api/dept/' + subject + '/?format=json')
    classdata = response.json()
    #print(classdata)
    return render(request, 'testapp/course.html', {'classdata':classdata})

def favorite_post(request, fav_id):
    postObj = get_object_or_404(Post, id=fav_id)
    postObj.favorite.add(request.user)
    return redirect('testapp:index')

def favorite_post_from_search(request, fav_id):
    postObj = get_object_or_404(Post, id=fav_id)
    postObj.favorite.add(request.user)
    return redirect('testapp:search')

def remove_favorite(request, fav_id):
    postObj = get_object_or_404(Post, id=fav_id)
    postObj.favorite.remove(request.user)
    return redirect('testapp:index')
    
def remove_favorite_from_fav(request, fav_id):
    '''
    Removes a favorite specificially from the favorites page
    '''
    postObj = get_object_or_404(Post, id=fav_id)
    postObj.favorite.remove(request.user)
    return redirect('testapp:favorites')

def remove_favorite_from_search(request, fav_id):
    '''
    Removes a favorite specificially from the search for posts page
    '''
    postObj = get_object_or_404(Post, id=fav_id)
    postObj.favorite.remove(request.user)
    return redirect('testapp:search')

class FavoritesView(LoginRequiredMixin, generic.ListView):
    template_name = 'testapp/favorites.html'
    #context_object_name = 'post_list'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Post.objects.filter(favorite=self.request.user)
        else:
            return None

class ProfileView(LoginRequiredMixin, generic.ListView):
    template_name = 'testapp/profile.html'
    def get_queryset(self):
        return Profile.objects.all()

# class UpdateProfile(UpdateView):
#     model = Profile
#     fields = ['name', 'year', 'major']
#     template_name = 'testapp/update_profile.html'
    # def get_object(self, *args, **kwargs):
    #     user = get_object_or_404(User, pk=self.kwargs['pk'])

#     def get_success_url(self, *args, **kwargs):
#         return redirect('testapp:profile')

class UpdateProfileView(LoginRequiredMixin, generic.DetailView):
    model = Profile
    template_name = 'testapp/update_profile.html'
    context_object_name = 'profile'

    def get_object(self, *args, **kwargs):
        user = get_object_or_404(User, pk=self.kwargs['pk'])
        return Profile.objects.get(user=user)

def updateProfile(request, pk):
    try:
        user = get_object_or_404(User, pk=pk)
        Profile.objects.filter(user=user).update(name=request.POST['name'], year=request.POST['year'], major=request.POST['major'])
    except(KeyError, ):
        return render(request, 'testapp/update_profile.html', {
            'error_message': "Please fill out all inputs",
        })
    else:
        return HttpResponseRedirect(reverse('testapp:profile'))

class ThreadList(LoginRequiredMixin, generic.ListView):
    template_name = 'testapp/thread_list.html'
    context_object_name = 'thread_list'

    def get_queryset(self):
        return Thread.objects.filter(Q(user1=self.request.user) | Q(user2=self.request.user))

class ThreadCreate(LoginRequiredMixin, generic.TemplateView):
    model = Thread
    template_name = 'testapp/create_thread.html'

def createThread(request):
    try:
        if User.objects.filter(username=request.POST['reciever']).exists():
            if request.POST['subject'] != "":
                Thread.objects.create(user1=User.objects.get(username=request.POST['reciever']), user2=request.user, subject_text=request.POST['subject'])
            else:
                Thread.objects.create(user1=User.objects.get(username=request.POST['reciever']), user2=request.user)
        else:
            return render(request, 'testapp/create_thread.html', {
                'error_message': "Please enter a valid username.",
            })
    except(KeyError, ):
        return render(request,'testapp/create_thread.html', {
            'error_message': "You didn't fill in an input.",
        })
    else:
        return HttpResponseRedirect(reverse('testapp:threads'))

class addNewFriend(LoginRequiredMixin, generic.DetailView):
    model = Profile
    template_name = 'testapp/add_friend.html'
    context_object_name = 'profile'

    def get_object(self, *args, **kwargs):
        user = get_object_or_404(User, pk=self.kwargs['pk'])
        return Profile.objects.get(user=user)

#working on this
def addFriend(request,pk):
    try:
        userObj = get_object_or_404(User,pk=pk)
        if User.objects.filter(username=request.POST['reciever']).exists():
            print('COOL!!!!!!!!!!!!!!!!!')
            buddy = User.objects.filter(username=request.POST['reciever']).first()
            userObj.profile.friends.add(buddy)
        else:
            return render(request, 'testapp/add_friend.html', {
                'error_message': "Please enter a valid username",
            })
    except(KeyError, ):
        return render(request,'testapp/add_friend.html', {
            'error_message': "No username was inputed.",
        })
    else:
        return HttpResponseRedirect(reverse('testapp:profile'))

class ThreadView(LoginRequiredMixin, generic.ListView):
    template_name = 'testapp/thread_view.html'
    context_object_name = 'message_list'

    def get_queryset(self):
        return Message.objects.filter(thread__pk__contains=self.kwargs['pk'])

    def get_context_data(self, *args, **kwargs):
        context = super(ThreadView, self).get_context_data(*args, **kwargs)
        context['thread_pk'] = self.kwargs['pk']
        threadObj = get_object_or_404(Thread, pk=self.kwargs['pk'])
        if threadObj.user1 != self.request.user:
            context['thread_username'] = threadObj.user1.username
        else:
            context['thread_username'] = threadObj.user2.username
        return context

def createMessage(request, pk):
    try:
        threadObj = get_object_or_404(Thread, pk=pk)
        if request.POST['message'] == "":
            messages = Message.objects.filter(thread__pk__contains=pk)
            if threadObj.user1 != request.user:
                return render(request,'testapp/thread_view.html', {
                'error_message': "You didn't fill in a message.",
                'thread_pk': pk,
                'thread_username': threadObj.user1.username,
                'message_list': messages
                })
            else:
                return render(request,'testapp/thread_view.html', {

testapp/templates/testapp/add_friend.html
{% include "testapp/header.html" %}

<div class="card">
    <div class="card-body text-center">
        <form method="POST" action="{% url 'testapp:add_friend' user.pk %}">
            {% csrf_token %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <fieldset>
                <label>Friend Username:</label>
                <input type="text" name="reciever" id="1" value="" class="form-control">
            </fieldset>
            <div class="text-center">
                <input type="submit" value="Add Friend" class="my-4 btn btn-primary text-center">
            </div>
        </form>
    </div>
</div>

testapp/templates/testapp/course.html
{% include "testapp/header.html" %}

<div class="container-fluid d-flex align-items-center justify-content-center">
    {% if classdata %}
        <div class="jumbotron text-center">
            <h1 style="color:blue;">You are looking at classes in: <strong>{{ classdata.0.subject }}</strong></h1>
        </div>
        </div>

        <div class="d-flex justify-content-center">

            <body>
                {% block content %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Subject</th>
                            <th>Catalog Number</th>
                            <th>Course Section</th>
                            <th>Description</th>
                            <th>Instructor</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for class in classdata %}
                        <tr>
                            <td>{{ class.subject }}</td>
                            <td>{{ class.catalog_number }}</td>
                            <td>{{ class.course_section }}</td>
                            <td>{{ class.description }}</td>
                            <td>{{ class.instructor.name }}</td>
                            <td><button class="btn btn-primary">
                                <a href="{% url 'testapp:createPostFromClass' class.subject class.catalog_number %}" class="text-decoration-none text-white">Make a Post!</a>
                            </button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endblock %}
            </body>
        </div>
    {% else %}
        <p>That department pneumonic does not exist.</p>
    {% endif %}
</div>

testapp/templates/testapp/create_thread.html
{% include "testapp/header.html" %}

<div class="card">
    <div class="card-body text-center">
        <p class="h3 mb-3">Create a Thread:</p>
        <form method="POST" action="{% url 'testapp:create_thread' %}">
            {% csrf_token %}
            {% if error_message %}<p class="alert alert-danger"><strong>{{ error_message }}</strong></p>{% endif %}
            <fieldset>
                <div class="mx-auto col-sm-3">
                    <label>User to Message:<span class="require text-danger"> *</span></label>
                    <input type="text" name="reciever" id="1" value="" class="form-control">
                </div>
            </fieldset>
            <fieldset>
                <div class="mx-auto col-sm-3">
                    <label>Subject:</label>
                    <input type="text" name="subject" id="2" value="" class="form-control">
                </div>
            </fieldset>
            <div class="text-center">
                <input type="submit" value="Create Thread" class="my-4 btn btn-primary text-center">
            </div>
        </form>
        <button type="button" class="btn btn-rounded btn-lg">
            <a class="nav-link" href="{% url 'testapp:threads' %}">Cancel</a>
        </button>
    </div>
</div>

testapp/templates/testapp/header.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}

<div class="jumbotron jumbotron-fluid text-center">
    <div class="container">
      <h1 class="display-4">Textbook Listing</h1>
      <p class="lead">This website allows you to sell and buy textbooks. &#128214;</p>
    </div>
</div>

<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/testapp/">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'testapp:post' %}">Create a Listing<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'testapp:classsubject' %}">Search for Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'testapp:search' %}">Search for Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'testapp:favorites' %}">Favorites</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'testapp:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'testapp:threads' %}">Messages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'testapp:add_friend' user.id %}">Add Friends</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="navbar-brand mb-0 h1 fs-3">Hello {{ user.username }}.</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-danger" href="/logout" role="button">Logout</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="navbar-link" href="/logout">Logout</a>
                </li> -->
                <!-- <form class="form-inline">
                    <input class="form-control" id="anythingSearch" type="text" placeholder="Search" aria-label="Search">
                </form> -->
            </ul>
        </div>
    </div>
</nav>
<hr>
<br/>

testapp/templates/testapp/index.html
{% include "testapp/header.html" %}

<div class="container-fluid d-flex align-items-center justify-content-center">
<!-- <div class="card-deck"> -->
        {% if post_list %}
            <div class="card-group">
                <ul style="list-style: none;">
                    {% for post in post_list %}
                        <li>
                            <div class="card text-white bg-dark mb-3" style="max-width: 40rem;">
                                <div class="card-body text-center">
                                    <h5 class="card-title">{{post.post_title}}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">{{post.associated_dept}} {{post.course_id}}</h6>
                                    {% if post.post_creator %}
                                        <h6 class="card-subtitle mb-2 text-muted">{{post.post_creator.username}}</h6>
                                    {% endif %}
                                    <p class="card-text">{{post.post_text}}</p>
                                    <!-- <p class="card-text"><small class="text-muted">Last updated {{post.pub_date}}</small></p> -->
                                    <!-- <a href="#" class="card-link">Card link</a> -->
                                    <!-- <a href="#" class="card-link">Another link</a> -->
                                    <!-- <div class="col"> -->
                                    <!-- <h4>{{post.post_title}} {{post.associated_dept}}</h4> -->
                                    <!-- <p class="lead"> {{post.post_text}}</p> -->
                                    <!-- <p>{{post.pub_date}}</p> -->
                                    <!-- <div class="form-check" style="width:auto;">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">Interested?</label>
        </div> -->
                                    <!-- <hr> -->
                                    
                                </div>
                                <div class="card-footer">
                                    <div class="col text-center">
                                        {% if user in post.favorite.all %}
                                        <form method='POST' action="{% url 'testapp:remove_favorite' post.id %}">
                                            {% csrf_token %}
                                            <input type='hidden' name='post' value={{ post.id }}>
                                            <button type='submit' class = "btn btn-danger btn-sm button-center">Unfavorite</button>
                                        </form>
                                        {% else %}
                                        <form method='POST' action="{% url 'testapp:favorite_post' post.id %}">
                                            {% csrf_token %}
                                            <input type='hidden' name='post' value={{ post.id }}>
                                            <button type='submit' class = "btn btn-primary btn-sm button-center">Favorite</button>
                                        </form>
                                        {% endif %}
                                        
                                    {% if post.favorite.count == 1%}
                                    <p class="card-text">{{post.favorite.count}} favorite</p>
                                    {% else %}
                                    <p class="card-text">{{post.favorite.count}} favorites</p>
                                    {% endif %}
                                    </div>
                                    <small class="text-muted">Last updated {{post.pub_date}}</small>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% else %}
            <p>No posts are available.</p>
        {% endif %}
</div>

testapp/templates/testapp/profile.html
{% include "testapp/header.html" %}

    <!-- <https://mdbootstrap.com/docs/standard/extended/profiles/  Help on profile page!> -->
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-20">
            <div class="col-md-12 col-xl-4">
                <div class="card" style="border-radius: 5px;">
                    <div class="card-body text-center">
                        <div class="mt-3 mb-4">
                        </div>
                        <h4 class="mb-2">{{ user.username }}</h4>
                        <p class="text-muted mb-4">
                            {{ user.profile.name }}
                        </p>
                        <p>
                            {{ user.profile.year }} Year <span class="mx-2">|</span> Major: {{ user.profile.major }}
                        </p>

                        <!-- <button type="button" class="btn btn-primary btn-rounded btn-lg">
                            <a class="link-light text-decoration-none" href="{% url 'testapp:add_friend' user.pk %}"> Add Friend</a>
                        </button> -->


                        <button type="button" class="btn btn-rounded btn-lg">
                            <a class="nav-link" href="{% url 'testapp:update_profile_view' user.pk %}">Update Profile</a>
                        </button>

                        <!-- <button type="button" class="btn btn-primary btn-rounded btn-lg">
    <a class="nav-link" href="{% url 'testapp:update_profile' user.pk%}">Update Profile</a>
        </button> -->
                        <!-- <form method='POST' action="{% url 'testapp:update_profile_view' user.pk %}">
         {% csrf_token %}
    <input type='hidden' name='post' value={{ user.pk }}>
        <button type='submit' class = "btn btn-primary btn-sm button-center">Update Profile</button>
    </form> -->
                        <!--https://stackoverflow.com/questions/837237/how-do-i-check-for-last-loop-iteration-in-django-template -->
                        <!-- <div class="d-flex justify-content-between text-center mt-5 mb-2"> -->
                        <div class="card-footer">
                            <div class="col text-center">
                                Friends: <br>
                                {% for friend in user.profile.friends.all %}
                                <tr>
                                    <div class="row"></div>
                                        {% if forloop.last %}
                                        <td>{{ friend }} </td>
                                        {% else %}
                                        <td>{{ friend }}, </td>
                                        {% endif %}
                                    </div>
                                </tr>
                                {% endfor %}
                            </div>
                        </div> 
                    </div>
            </div>
        </div>
    </div>

testapp/templates/testapp/thread_list.html
{% include "testapp/header.html" %}

<div class="card">
    <div class="card-body text-center">
        <p class="h3">&#128172; Your Messages:</p>
    </div>
</div>

<div class="container-fluid d-flex align-items-center justify-content-center">
    <button type="button" class="btn btn-rounded btn-lg">
        <a class="nav-link" href="{% url 'testapp:thread_creation' %}">Create New Thread!</a>
    </button>
</div>
    {% if thread_list %}
    {% for thread in thread_list %}
    <div class="card">
        <div class="card-body text-center">
            {% if thread.user1 != user %}
            <p>
                <a class="nav-link" href="{% url 'testapp:thread_view' thread.pk %}">{{thread.subject_text}} - {{thread.user1.username}}</a>
            </p>
            {% else %}
            <p>
                <a class="nav-link" href="{% url 'testapp:thread_view' thread.pk %}">{{thread.subject_text}} - {{thread.user2.username}}</a>
            </p>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="card">
        <div class="card-body text-center">
            <p>No threads are available.</p>
        </div>
    </div>
    {% endif %}