b_04_textbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('testapp/', include('testapp.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

testapp/urls.py
from django.urls import path, reverse

from . import views

app_name = 'testapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post', views.PostCreate.as_view(), name='post'),
    path('createPost', views.createPost, name='createPost'),
    path('createPost/<dept>/<id>', views.createPostFromClass, name='createPostFromClass'),
    path('course', views.course, name='course'),
    path('classsubject', views.ClassSubjectCreate.as_view(success_url = '/testapp/course'), name='classsubject'),
    path('<int:fav_id>/favorite_post', views.favorite_post, name='favorite_post'),
    path('<int:fav_id>/favorite_post_from_search', views.favorite_post_from_search, name='favorite_post_from_search'),
    path('<int:fav_id>/remove_favorite', views.remove_favorite, name='remove_favorite'),
    path('<int:fav_id>/remove_favorite_from_fav', views.remove_favorite_from_fav, name='remove_favorite_from_fav'),
    path('<int:fav_id>/remove_favorite_from_search',views.remove_favorite_from_search, name = 'remove_favorite_from_search'),
    path('favorites', views.FavoritesView.as_view(), name='favorites'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('profile/<pk>/edit', views.UpdateProfileView.as_view(), name='update_profile_view'),
    path('profile/<pk>/update', views.updateProfile, name='update_profile'),
    path('profile/<pk>/add_friend', views.addFriend, name='add_friend'),
    path('profile/<pk>/alt', views.addNewFriend.as_view(), name='add_new_friend'),
    path('threads', views.ThreadList.as_view(), name='threads'),
    path('threads/create', views.ThreadCreate.as_view(), name='thread_creation'),
    path('threads/createThread', views.createThread, name='create_thread'),
    path('threads/<pk>', views.ThreadView.as_view(), name='thread_view'),
    path('threads/<pk>/createMessage', views.createMessage, name='create_message'),
    path('post_search', views.searchView.as_view(), name='search'),
]

templates/index.html
{% load socialaccount %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}

<html>
<body>

    <div class="jumbotron jumbotron-fluid text-center">
        <div class="container">
            <h1 class="display-4">Textbook Exchange App</h1>
        </div>
    </div>


    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'testapp:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
    <hr>
    <br />

    <div>

    </div>

    <div class="container text-center">
        <div class="card-body text-center">
            <p class="h1 mb-4">&#128075; Looking for a cheap textbook?</p>
            <p class="h5 my-4">With our website you can:</p>
            <p class="my-2">&#128269; Search for textbooks being sold</p>
            <p class="my-2">&#128218; Keep a list of your favorite posts</p>
            <p class="my-2">&#128483; Message other students selling/buying textbooks</p>
            <p class="h5 mt-4">...And more! Sign up today and we'll connect you to the textbooks you need!</p>
        </div>
        {% if user.is_authenticated %}
        <p><strong> Welcome, You are logged in as {{ user.username }}</strong></p>
        <a href="/logout">Logout With Google</a>
        {% else %}
        <form action="{% provider_login_url 'google' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="my-2 btn btn-primary text-center">Login With Google</button>
        </form>
        <!-- <a href="{% provider_login_url 'google' %}">Login With Google</a> -->
        {% endif %}
    </div>

</body>
</html>